Clean up kubernetes nodepool destroy
I noticed several exceptions like the one below in the E2E logs:

    Exception: PG::ForeignKeyViolation - ERROR:  update or delete on table "vm" violates foreign key constraint "kubernetes_node_vm_id_fkey" on table "kubernetes_node"
DETAIL:  Key (id)=(e756628c-a84d-8b74-8696-8f20869a3c04) is still referenced from table "kubernetes_node".

These errors eventually disappear, but they make the logs noisy and
harder to read.

The root cause is that we trigger the destruction of vms and nodes of
the nodepool first, and then wait for the nodes to be deleted. However,
the vms can’t be deleted until the corresponding kubernetes node row is
removed due to the foreign key constraint.

We don’t need to destroy vms separately, since node already handles the
destruction of its vm.