Fix issue in rake spec_separate
Disconnect all databases before the loop over the files, as the
file using POSTGRES_MONITOR_DB does not use cached schema, and
issuing a query after forking can cause problems such as:

```
ERROR: problems loading model/postgres/postgres_lsn_monitor.rb: Sequel::DatabaseDisconnectError: PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request
```