Fail more gracefully if the validated value is nil
I saw multiple web requests failing with the following error message:

    Jan 4 11:11:57  app[web]  NoMethodError: undefined method `match' for nil:NilClass
    Jan 4 11:11:57  app[web]  /app/lib/validation.rb:62:in `validate_os_user_name'

It's more appropriate to return a validation error rather than an HTTP
500 if these values are nil.