Revert aws-sdk-s3 to 1.163.0 from 1.166.0
Dependabot upgraded it at 0eb6a12f

But it fails at production with the following exception

```
TypeError: superclass mismatch for class AbortIncompleteMultipartUpload

app/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/types.rb:31:in `<module:Types>'
app/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/types.rb:11:in `<module:S3>'
app/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/types.rb:10:in `<top (required)>'
internal:/app/vendor/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
internal:/app/vendor/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
app/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/client_api.rb:626:in `<module:ClientApi>'
app/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/client_api.rb:13:in `<module:S3>'
app/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/client_api.rb:11:in `<top (required)>'
internal:/app/vendor/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
internal:/app/vendor/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
app/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/client.rb:79:in `<class:Client>'
app/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/client.rb:73:in `<module:S3>'
app/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/client.rb:60:in `<top (required)>'
internal:/app/vendor/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
internal:/app/vendor/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
app/model/github/github_repository.rb:31:in `blob_storage_client'

```

But I couldn't reproduce it at local