Require "shellwords" in nexus.rb
Previously when I started ./bin/respirate I sometimes saw errors
like:

```
nexus.rb:196:in `create_ipsec_tunnel': undefined method `shellescape' for "vm4a0dt9":String (NoMethodError)

    q_dst_name = dst_vm.inhost_name.shellescape
```