Do not fail rake tasks if dev gems not installed
We don't install :development and :test gems in production environment.
Any rake task is failed if we require dev dependencies in any part of
Rakefile. We rescue same error for :spec task too.

    rake aborted!
    LoadError: cannot load such file -- rubocop/rake_task
    <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in
    `require'
    <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in
    `require'
    /app/Rakefile:151:in `block in <top (required)>'
    /app/Rakefile:146:in `<top (required)>'
    (See full trace by running task with
    --trace)