Reorder kubernetes cluster destroy
I noticed several exceptions like the one below in the E2E logs:

    Exception: PG::ForeignKeyViolation - ERROR:  update or delete on table "load_balancer" violates foreign key constraint "kubernetes_cluster_api_server_lb_id_fkey" on table "kubernetes_cluster" DETAIL:  Key (id)=(1cab492d-8ec4-8c2b-8d29-877bd664a5f1) is still referenced from table "kubernetes_cluster".

These errors eventually disappear, but they make the logs noisy and
harder to read.

The root cause is that we trigger the destruction of load balancers and
nodes of the cluster first, and then wait for the nodes to be deleted.
However, the load balancers can’t be deleted until the corresponding
Kubernetes cluster row is removed due to the foreign key constraint.

To fix this, it’s better to first validate that the node destruction is
complete, and only then trigger the destruction of the load balancers.

Also, we don’t need to destroy cp_vms separately, since cluster.nodes
already handles the destruction of control plane VMs.