Update rubocop and apply fixes
The new version fails with the following exception

    Error: The `Sequel/ColumnDefault` cop has been removed since ColumnDefault cop since it's mostly outdated advice. Details [#33](https://github.com/rubocop/rubocop-sequel/issues/32).
    (obsolete configuration found in .rubocop.yml, please update it)
    RuboCop failed!
    Running RuboCop...

Check the author of the linked issue [^1] (spoiler alert: @fdr)

Also I disabled new `Sequel/IrreversibleMigration` cop since we don't
try to make our migrations reversible [^2].

[^1]: https://github.com/rubocop/rubocop-sequel/issues/32
[^2]: https://github.com/ubicloud/ubicloud/pull/239