Fix rspec `.or` chain
In rspec, when you want to use `.or()`, you need to use it with two
complete matchers, not chain it after a matcher.

It fails for the second case

     1) Scheduling::Dispatcher#repartition_thread repartitions for new processes and stale processes
     Failure/Error: expect(args).to eq([{num_partitions: 2}, {num_partitions: 3}]).or([{num_partitions: 3}])

     NoMethodError:
       undefined method 'matches?' for an instance of Array
     # ./spec/scheduling/dispatcher_spec.rb:60:in 'block (3 levels) in <top (required)>'