Make Vm#load_balancer_state handle missing VM ports
We had a couple production exceptions related to this:

```
NoMethodError - undefined method 'state' for nil
/app/model/vm.rb:64:in 'block in Vm#load_balancer_state'
```

Unless there is a way to avoid the situation and ensure that if a VM has
a load balancer, that the VM ports must be available, we need to handle
this case.