Fix pagination issue of finding cloudwatch_policy
Since the default page element count is 100, without this, we are
hitting:
NoMethodError: undefined method 'arn' for nil (NoMethodError)

iam_client.attach_role_policy({role_name:, policy_arn: cloudwatch_policy.arn})