Handle empty network interface
We’ve seen cases where the network interface returns nil temporarily and
succeeds in subsequent runs.

Instead of raising an exception, it's better to handle this condition
gracefully and nap.

    {
      "backtrace": [
        "/app/prog/vnet/aws/nic_nexus.rb:103:in 'Prog::Vnet::Aws::NicNexus#assign_ipv6_address'",
        ...
      ],
      "class": "NoMethodError",
      "message": "undefined method 'ipv_6_addresses' for nil"
    }