Nap instead of failing if AWS instance reservations are empty
I saw intermittent `Vm::Aws::Nexus.wait_instance_created` failures in
production with `NoMethodError: undefined method 'instances' for nil`.

These errors resolve themselves over time and indicate that the AWS API
can return an empty reservations list during initial requests.

Instead of raising an exception in this case, we should nap until
reservations are available.