Downgrade golangci/golangci-lint-action to v6
I merged #3047, but it seems to have broken the CI. The
golangci/golangci-lint-action@v7 requires using golangci-lint v2, but v2
raises the following error. I didn't notice it because cli-ci didn't run
on that PR. Thanks to the previous commit, cli-ci will run when there
are changes.

    Error: cli/ubi.go:74:23: Error return value of `resp.Body.Close` is not checked (errcheck)
    	defer resp.Body.Close()
    	                     ^
    1 issues:
    * errcheck: 1