Avoid database error if there is an invoice in the future
We have had multiple production exceptions of the form:

```
PG::DataException
ERROR:  range lower bound must be less than or equal to range upper bound
CONTEXT:  unnamed portal parameter $1 = '...'
```

that have this code in the backtrace. One possible cause of this
is an invoice with an end date in the future. I'm not sure this is
the cause, and even if it is, maybe we should do something to prevent
it.  However, this change should at least avoid the exception.

While here, remove redundant Time.now calls, and make sure the times
are in UTC.