Update js packages
Dependabot can't update package-lock.json correctly and it fails with
the following exception at #4034

```
    npx redocly lint openapi/openapi.yml --config openapi/redocly.yml
        node:internal/modules/cjs/loader:1410
          const err = new Error(message);
                          ^

    Error: Cannot find module 'yaml'
    Require stack:
    - /home/runner/work/ubicloud/ubicloud/node_modules/redoc/bundles/redoc.lib.js
        at Module._resolveFilename (node:internal/modules/cjs/loader:1410:15)
        at defaultResolveImpl (node:internal/modules/cjs/loader:1051:19)
        at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1056:22)
        at Module._load (node:internal/modules/cjs/loader:1219:37)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)
        at Module.require (node:internal/modules/cjs/loader:1493:12)
        at require (node:internal/modules/helpers:152:16)
        at 115 (/home/runner/work/ubicloud/ubicloud/node_modules/redoc/bundles/redoc.lib.js:2:88708)
        at r (/home/runner/work/ubicloud/ubicloud/node_modules/redoc/bundles/redoc.lib.js:2:89093) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/runner/work/ubicloud/ubicloud/node_modules/redoc/bundles/redoc.lib.js'
     ]
    }

    Node.js v24.6.0
    rake aborted!
    Command failed with status (1): [npx redocly lint openapi/openapi.yml --config openapi/redocly.yml]
    /home/runner/work/ubicloud/ubicloud/Rakefile:481:in 'block (2 levels) in <top (required)>'
    /home/runner/work/ubicloud/ubicloud/vendor/bundle/ruby/3.4.0/gems/rake-13.3.0/exe/rake:27:in '<top (required)>'
    /opt/hostedtoolcache/Ruby/3.4.7/x64/bin/bundle:25:in 'Kernel#load'
    /opt/hostedtoolcache/Ruby/3.4.7/x64/bin/bundle:25:in '<main>'
    Tasks: TOP => linter:openapi
    (See full trace by running task with --trace)
```